# Generated by Django 4.1.7 on 2023-03-18 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, max_length=200, validators=[django.core.validators.MinLengthValidator(20)])),
                ('Content', models.TextField(error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, validators=[django.core.validators.MinLengthValidator(200)])),
                ('Category', models.CharField(error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT'), ('THRASH', 'THRASH')], error_messages={'invalid': 'Enter a valid value', 'required': 'This field is required'}, max_length=100)),
            ],
        ),
    ]
