# Generated by Django 4.1.7 on 2023-03-18 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_posts_category_alter_posts_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Category',
            field=models.CharField(error_messages={'invalid': 'Isi tidak Sesuai!', 'invalid_choice': 'Pilihan tidak tersedia', 'min_length': 'Berisi %(show_value)d, minimal %(limit_value)d', 'required': 'Kolom wajib di isi!'}, max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Content',
            field=models.TextField(error_messages={'invalid': 'Isi tidak Sesuai!', 'invalid_choice': 'Pilihan tidak tersedia', 'min_length': 'Berisi %(show_value)d, minimal %(limit_value)d', 'required': 'Kolom wajib di isi!'}, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT'), ('THRASH', 'THRASH')], error_messages={'invalid': 'Isi tidak Sesuai!', 'invalid_choice': 'Pilihan tidak tersedia', 'min_length': 'Berisi %(show_value)d, minimal %(limit_value)d', 'required': 'Kolom wajib di isi!'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Title',
            field=models.CharField(error_messages={'invalid': 'Isi tidak Sesuai!', 'invalid_choice': 'Pilihan tidak tersedia', 'min_length': 'Berisi %(show_value)d, minimal %(limit_value)d', 'required': 'Kolom wajib di isi!'}, max_length=200, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
